### ISSUE TITLE
ERR_INVALID_ARG_TYPE

### ISSUE THREAD

**Issue by DuckyGit** [micahlt/modchat#54]
Here is the error
`2021-01-28T00:19:18.271927+00:00 app[web.1]: 
2021-01-28T00:19:18.271944+00:00 app[web.1]: > modchat@1.5.1 start /app
2021-01-28T00:19:18.271944+00:00 app[web.1]: > node index.js
2021-01-28T00:19:18.271945+00:00 app[web.1]: 
2021-01-28T00:19:18.340294+00:00 app[web.1]: internal/crypto/util.js:84
2021-01-28T00:19:18.340296+00:00 app[web.1]:     throw new ERR_INVALID_ARG_TYPE(
2021-01-28T00:19:18.340296+00:00 app[web.1]:     ^
2021-01-28T00:19:18.340296+00:00 app[web.1]: 
2021-01-28T00:19:18.340297+00:00 app[web.1]: TypeError [ERR_INVALID_ARG_TYPE]: The "password" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
2021-01-28T00:19:18.340297+00:00 app[web.1]:     at Cipher.createCipher (internal/crypto/cipher.js:112:14)
2021-01-28T00:19:18.340298+00:00 app[web.1]:     at new Cipher (internal/crypto/cipher.js:128:16)
2021-01-28T00:19:18.340298+00:00 app[web.1]:     at Object.createCipher (crypto.js:119:10)
2021-01-28T00:19:18.340298+00:00 app[web.1]:     at Object.deprecated (internal/util.js:89:15)
2021-01-28T00:19:18.340298+00:00 app[web.1]:     at Object.<anonymous> (/app/index.js:6:21)
2021-01-28T00:19:18.340299+00:00 app[web.1]:     at Module._compile (internal/modules/cjs/loader.js:999:30)
2021-01-28T00:19:18.340299+00:00 app[web.1]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
2021-01-28T00:19:18.340299+00:00 app[web.1]:     at Module.load (internal/modules/cjs/loader.js:863:32)
2021-01-28T00:19:18.340300+00:00 app[web.1]:     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
2021-01-28T00:19:18.340300+00:00 app[web.1]:     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
2021-01-28T00:19:18.340301+00:00 app[web.1]:   code: 'ERR_INVALID_ARG_TYPE'
2021-01-28T00:19:18.340301+00:00 app[web.1]: }
2021-01-28T00:19:18.350165+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2021-01-28T00:19:18.350384+00:00 app[web.1]: npm ERR! errno 1
2021-01-28T00:19:18.354981+00:00 app[web.1]: npm ERR! modchat@1.5.1 start: `node index.js`
2021-01-28T00:19:18.355083+00:00 app[web.1]: npm ERR! Exit status 1
2021-01-28T00:19:18.355197+00:00 app[web.1]: npm ERR! 
2021-01-28T00:19:18.355286+00:00 app[web.1]: npm ERR! Failed at the modchat@1.5.1 start script.
2021-01-28T00:19:18.355374+00:00 app[web.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2021-01-28T00:19:18.363490+00:00 app[web.1]: 
2021-01-28T00:19:18.363632+00:00 app[web.1]: npm ERR! A complete log of this run can be found in:
2021-01-28T00:19:18.363717+00:00 app[web.1]: npm ERR!     /app/.npm/_logs/2021-01-28T00_19_18_355Z-debug.log`

**Comment by contourcode** [comment]
This won't really help that much. Could you describe how the error came?

**Comment by DuckyGit** [comment]
When i try to start it
